dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - [ $PYTHON = "3.5" ] || pip3 install black
script:
  - [ $PYTHON = "3.5" ] || black --check $(git ls-files '*.py')
  - python3 -m unittest -vb
